### ISSUE TITLE
Test and fix the no-prompt option

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#1]
The `--noprompt` command line argument and it´s documentation needs to be checked.

In the readme it was documented the following way: "exit and fail on user prompts".
The code might always be executing the first one.

**Test this in the code and make sure it was documented accordingly.**

**Comment by KGergo88** [comment]
@holzkohlengrill, The documents and the code seems to be aligned. I did not find any errors.
Please review and make corrections if needed.

**Comment by holzkohlengrill** [comment]
Done in #14 .
