### ISSUE TITLE
Emma-vis --dir parameter handling

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#11]
The handling of the --dir parameter is quite strange in the Emma-vis:
  - This is not a required parameter, but the memStats input files will be searched for in this folder (See helper.py::getLastModFileOrPrompt())
  - If the path given in the --dir parameter does not exist, then it will be created, which does not make sense, because then it surely does not contain the memStats input files
  - If no --dir is given, then it´s value will be default set to None. This leads that the os.path.join() call fails in emma_vis_libs.helper.getLastModFileOrPrompt()

### TODO
- [x] Please review this part of the code and make a decision how it should be implemented
- [x] Implement the new design
- [x] Update documentation

**Comment by holzkohlengrill** [comment]
## Implementation behaviour

1. If only `projectDir` is given: I/O path = `projectDir`
2. If `projectDir` and `inOutDir` is given: I/O path = `inOutDir`; `projectDir` = projectConfig
3. If `projectDir`, `inOutDir` and `subDir` is given; I/O path = `inOutDir` + `subDir`; `projectDir` = projectConfig

## Implementation details:
At the end of argument parsing `inOutDir` and `subDir` get deleted. There is an additional `inOutDir` which contains the resulting paths according to the rules stated above.

=====

* I/O path: path containing `memStats` and where `results` will be written to
* projectConfig: all `*.json` configuration files
