### ISSUE TITLE
Remove non pypiscout Emma command line prints

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#12]
The new `pypiscout` has the feature to disable log printing based on the log levels.
With this functionality it is possible to completely turn off logging.

It was detected, that even when the logging turned off, there are still messages printed. These are messages that are made with the `print()` python function.

### TODO
  - Review all the print commands whether it is possible to replace them with `pypiscout` calls.

**Comment by holzkohlengrill** [comment]
I think at least in some prompt cases an ordinary `print()` will be used. That was done by purpose. 

However feel free to bring in your findings and we will discuss about that.

**Comment by holzkohlengrill** [comment]
Listing of necessary `print()`s.

| File:Line                                              | Rationale                                                                              |
| ------------------------------------------------------ | -------------------------------------------------------------------------------------- |
| emma_vis_libs/helper.py:65                             | File listing; (`sc().info` would decrease readability)                                 |
| genDoc/_genCallGraphs.py:176                           | Newline after subprocess call                                                          |
| emma_vis_libs/dataVisualiserObjects.py:47              | Print of vis results dataframe                                                         |
| emma_vis_libs/dataVisualiserSections.py:241            | Print of vis results dataframe                                                         |
| emma_vis_libs/dataVisualiserSections.py:242            | Print of vis results dataframe                                                         |
| emma_vis_libs/dataVisualiserSections.py:243            | Print of vis results dataframe                                                         |
| genDoc/genReadmeHtmlFromMd.py:107                      | Newline after a lot of flexible commands                                               |
| emma_delta_libs/FilePresenter.py:69                    | File listing; (`sc().info` would decrease readability)                                 |
| emma_delta_libs/FilePresenter.py:78                    | File listing; (`sc().info` would decrease readability)                                 |
| emma_delta_libs/FilePresenter.py:82                    | File listing; (`sc().info` would decrease readability)                                 |
| emma_vis_libs/dataVisualiserCategorisedSections.py:171 | Print of vis results dataframe                                                         |
| emma_vis_libs/dataVisualiserCategorisedSections.py:178 | Print of vis results dataframe                                                         |
| emma_libs/ghsConfiguration.py:155                      | Mapfile listing are a "sub-section" of the above scout message to increase readability |
| emma_libs/ghsConfiguration.py:195                      | File listing; (`sc().info` would decrease readability)                                 |
| emma_libs/ghsConfiguration.py:290                      | File listing; (`sc().info` would decrease readability)                                 |
