### ISSUE TITLE
TeamScale JSON output

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#23]
## Feature Description

In order to enable seamless integration to quality tools (TeamScale will be the first step towards this direction) Emma should generate some JSON output.

* TeamScale expects datain JSON format
    * Expects arbitrary tree (-> `path` tag) (non-code metric) in JSON format
* TeamScale docu (JSON, p. 231): https://www.cqse.eu/download/teamscale/userguide.pdf

**Comment by DariaPigasova** [comment]
Open point: `path` of TeamScale output
