### ISSUE TITLE
Provide Emma documentation via readthedocs

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#31]
## Feature Description

* It could be much more conveniant to read the documentation at [readthedocs](https://readthedocs.org/). 
* No `html` documentation anymore -> Less errors when not regenerated

**Comment by Patil2099** [comment]
@holzkohlengrill Can I work on this issue?

**Comment by holzkohlengrill** [comment]
Thanks @Patil2099 for your interest. However this issue is already ongoing and involves the creation of a new account.

If you want to contribute this tickets seem a good start in my opinion:

1. #28 
2. #30 
3. #14 
4. #20 

Probably it makes sense to start in this order.
