### ISSUE TITLE
Unfiltered callgraph pictures will not be created

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#4]
During the creation of the .png files from the unfiltered call graph dot files a segmentation fault happens. It seems that the current DPI value of 300 causes the problem. With a 200 DPI, the conversion succeeds.

### TODO:
  - Find out the max possible DPI value with we can still create pictures
  - Change the DPI setting in the constants
  -  Test the changes

**Comment by holzkohlengrill** [comment]
~I think this was already "fixed".~
~I decreased the DPI settings.~
~@KGergo88  please verify.~

`DPI_DOCUMENTATION` is used in `stringConstants.py`. Seems that is is still not changed.
