### ISSUE TITLE
`SECTIONS_TO_EXCLUDE` should be in a configuration file

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#43]
## Feature Description

`SECTIONS_TO_EXCLUDE` (find it [here](https://github.com/bmwcarit/Emma/blob/08a81612bf5fd8f587b50d61bf98c13e495e8f5b/Emma/shared_libs/stringConstants.py#L280)) contains kind of specific data. It would be better placed in the globalConfig file.

Define a default behaviour (= current behaviour with one exception (see below)) and add a weak warning notifying that this setting is not overwritten and the default `SECTIONS_TO_EXCLUDE` is currently active.

Exception: remove:
```
".unused_ram",
".mr_rw_NandFlashDataBuffer"
```
but keep the variable `SECTIONS_TO_EXCLUDE`.

* [ ] Update https://cc-github.bmwgroup.net/marcelschmalzlpartner/MAdZ-configs accordingly.

**Comment by DariaPigasova** [comment]
SECTIONS_TO_EXCLUDE - union of DWARF_SECTIONS and a set that can be defined per config ID.
If section to exclude is not defined in config ID, a weak warning should appear that sections to exclude are not defined in global config and only DWARF_SECTIONS will be excluded. If the flag "analyse_debug" is set, the weak warning should not appear.
