### ISSUE TITLE
Replace all prints with SCout messages

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#57]
# Description
 
To insure log level switching we need to remove all `print()`s and replace it with SCout messages.
Where really needed (i.e. for file presentation -> to user) the SCout basic implementation can/should be used.

Everything in genDoc etc. can be ignored.

## Expected behaviour

Correct message display according to log levels.

**Comment by DariaPigasova** [comment]
What should we do with prints in functions that are not used?

**Comment by holzkohlengrill** [comment]
Replace it with SCout messages if appropriate.

**Comment by DariaPigasova** [comment]
3698cbc808e09fe1dcae9a9747078d5506adaa14
