### ISSUE TITLE
Categorisation keywords as Emma dry run

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#6]
This should be like a "dry run". We need to run Emma in order to get all sections/objects from the map files. Then we auto-generate the categories config file based on the keyword file(s).

Currently `.csv` files are saved for such a run (which is the default behaviour for a normal run) which is not desired.

For a "keywords-run" no results should be stored.

TODO in: https://github.com/bmwcarit/Emma/blob/master/emma.py#L136 (**invalid link: check commit from Jul 2019**)

**Comment by DariaPigasova** [comment]
Was already implemented
