### ISSUE TITLE
PyCharm inspection detects wrong Markdown picture links

### ISSUE THREAD

**Issue by KGergo88** [bmwcarit/Emma#7]
![image](https://user-images.githubusercontent.com/17816598/61443802-807f2100-a94a-11e9-9da4-227cb4a06a1a.png)

Some picture links has an ending `width="XY%" /></div>` where the `/` after the `%` symbol seems to be extra. This will lead to a generated html where the `<p>` and `</p>` tags are not matched according to PyCharm.

PyCharm detects the error with the following pictures:
  - readme.html
    - classes_memoryManager.png
    - emma_filtered_profile.png
  - readme-vis.html
    - emma_vis_filtered.profile.png

### TODO
 - Examine the issue
 - Try to remove the extra `/` symbols and rerun PyCharm inspection
 - Check the generated .html files

**Comment by holzkohlengrill** [comment]
the `/` is wrong. Can be removed
